# Generated by Django 4.0.6 on 2022-08-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtracto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registered',
        ),
    ]
