# Generated by Django 4.0.6 on 2022-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracto', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
