# Generated by Django 4.0.6 on 2022-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_downloads',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
