# Generated by Django 4.0.6 on 2022-08-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile_no_of_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
